### ISSUE TITLE
Owo farmbot android 

### ISSUE THREAD

**Issue by EzHarshit** [Mid0aria/owofarmbot_stable#21]
Uhm idk but whenever I use this stable version and do all the process it shows at the end npm package error and for starting the bot .sh won't even work and node bot.js will show but idk some sort of package errors so many and last version 1.088 is working fine idk whats the issue pls fix that so we can enjoy stable version on Android too 🤓 and also there's one more issue regarding 1.088 version that it doesn't stop on captcha and continue to write commands so fix that all in stable version please

**Comment by Random-629671** [comment]
This stable version using some node module that refused to install on android tho
And the old bot (v1, which stay at v1.0.8.8) captcha detection didnt got the update yet. Dont use that

**Comment by Mid0aria** [comment]
the reason why it doesn't work on android is puppeteer. with puppeteer we solve auto voting and auto web captcha. I will make a special branch for Termux, but this branch will not have auto-voting and automatic web captcha, so be informed in advance

**Comment by EzHarshit** [comment]
> the reason why it doesn't work on android is puppeteer. with puppeteer we solve auto voting and auto web captcha. I will make a special branch for Termux, but this branch will not have auto-voting and automatic web captcha, so be informed in advance

Thanks in advance for that yayyyyyyy ❤️

**Comment by EzHarshit** [comment]
> This stable version using some node module that refused to install on android tho And the old bot (v1, which stay at v1.0.8.8) captcha detection didnt got the update yet. Dont use that

I use that still lol I just see screen whenever captcha i close script and rerun again after solving 🤓

**Comment by Mid0aria** [comment]
try resetting termux and reinstalling the farm bot from the beginning I think I fixed the problems

**Comment by Mid0aria** [comment]
fixed all errors https://github.com/Mid0aria/owofarmbot_stable/commit/22a35c2c421a24889a27a2324343888f7c420fe1

**Comment by EzHarshit** [comment]
> can u try resetting termux and reinstalling the farm bot from the beginning I think I fixed the problems

Yes ofc

**Comment by EzHarshit** [comment]
> fixed all errors [22a35c2](https://github.com/Mid0aria/owofarmbot_stable/commit/22a35c2c421a24889a27a2324343888f7c420fe1)

Yup it's working and bot commands are now being used like start stop paise is working great but the only issue is it opens inventory for start gems and there is no event so it keeps Opening inventory due to which owo says u too fast for me

**Comment by Mid0aria** [comment]
> > fixed all errors [22a35c2](https://github.com/Mid0aria/owofarmbot_stable/commit/22a35c2c421a24889a27a2324343888f7c420fe1)
> 
> Yup it's working and bot commands are now being used like start stop paise is working great but the only issue is it opens inventory for start gems and there is no event so it keeps Opening inventory due to which owo says u too fast for me

most likely a problem with the inventory control structure. I'll take a look when I get home.

**Comment by EzHarshit** [comment]
> > > fixed all errors [22a35c2](https://github.com/Mid0aria/owofarmbot_stable/commit/22a35c2c421a24889a27a2324343888f7c420fe1)
> > 
> > 
> > Yup it's working and bot commands are now being used like start stop paise is working great but the only issue is it opens inventory for start gems and there is no event so it keeps Opening inventory due to which owo says u too fast for me
> 
> most likely a problem with the inventory control structure. I'll take a look when I get home.

Thankssss ❤️

**Comment by EzHarshit** [comment]
> > > fixed all errors [22a35c2](https://github.com/Mid0aria/owofarmbot_stable/commit/22a35c2c421a24889a27a2324343888f7c420fe1)
> > 
> > 
> > Yup it's working and bot commands are now being used like start stop paise is working great but the only issue is it opens inventory for start gems and there is no event so it keeps Opening inventory due to which owo says u too fast for me
> 
> most likely a problem with the inventory control structure. I'll take a look when I get home.

![Screenshot_2024-12-24-14-00-03-608_com termux](https://github.com/user-attachments/assets/17947a23-b2e2-480a-9cbb-b15dd8c8d7ee)
This and due to this it wanna search in inventory so I kept inventory for false now

**Comment by EzHarshit** [comment]
> > > fixed all errors [22a35c2](https://github.com/Mid0aria/owofarmbot_stable/commit/22a35c2c421a24889a27a2324343888f7c420fe1)
> > 
> > 
> > Yup it's working and bot commands are now being used like start stop paise is working great but the only issue is it opens inventory for start gems and there is no event so it keeps Opening inventory due to which owo says u too fast for me
> 
> most likely a problem with the inventory control structure. I'll take a look when I get home.

And sir in this update u interchanged hunt battle interval ig coz min value acting as max according to previous version

**Comment by EzHarshit** [comment]
> > > > fixed all errors [22a35c2](https://github.com/Mid0aria/owofarmbot_stable/commit/22a35c2c421a24889a27a2324343888f7c420fe1)
> > > 
> > > 
> > > Yup it's working and bot commands are now being used like start stop paise is working great but the only issue is it opens inventory for start gems and there is no event so it keeps Opening inventory due to which owo says u too fast for me
> > 
> > 
> > most likely a problem with the inventory control structure. I'll take a look when I get home.
> 
> And sir in this update u interchanged hunt battle interval ig coz min value acting as max according to previous version

Although I interchanged the value and it's good now the only thing is 4th gem issue 🤓🤓

**Comment by waylayers** [comment]
> Although I interchanged the value and it's good now the only thing is 4th gem issue 🤓🤓

please remove the previous unrelated replies when you're quoting a comment

**Comment by EzHarshit** [comment]
> > > fixed all errors [22a35c2](https://github.com/Mid0aria/owofarmbot_stable/commit/22a35c2c421a24889a27a2324343888f7c420fe1)
> > 
> > 
> > Yup it's working and bot commands are now being used like start stop paise is working great but the only issue is it opens inventory for start gems and there is no event so it keeps Opening inventory due to which owo says u too fast for me
> 
> most likely a problem with the inventory control structure. I'll take a look when I get home.

And btw i fixed that by editing farm.js by typing nano ./utility/function/farm.js and I removed star from there so all good now 
![Screenshot_2024-12-24-20-02-55-373_com termux](https://github.com/user-attachments/assets/e1b7ca80-6243-46b0-b1a5-01c927a1a40f)
